# Name of output folder
sample_name: MrHAMER2_test

# Input FASTQ files. Can be a (zipped) FASTQ file or a folder containing (zipped) FASTQ files
input_fastq: test_files/MrHAMER2_test.fastq

# Reference genome
reference_fasta: "test_files/NL43_Complete.fa"

# BED file containing intervals with regions that are going to be analysed
targets_bed: test_files/regions.bed


############################
######### Optional #########
############################
#Would you like to run Chimera_Buster?
chimera_buster_on: True

#Mismatch tolerence for Chimera_Buster
#(modify at own risk, see Github page for more details.)
chimera_buster_MT: 1

#Would you like to run Chimera_Buster in High Sensitivity mode?
#(Only recommended for low input files)
chimera_buster_HS: True

#Minimap2 parameters
minimap2_param: "-ax map-ont -k 13"

# Max differences between UMI in read and UMI pattern
umi_errors: 1

# Min number of reads required for a consensus read
min_reads_per_cluster: 4

# Max number of 1D used for a consensus read
max_reads_per_cluster: 50

# Min overlap with target region
min_overlap: 0.13

# Balance forward and reverse 1D reads in clusters
balance_strands: True

# Medaka model used to compute consensus reads
medaka_model: "./test_files/r1041_e82_400bps_sup_v4.2.0_model.tar.gz"

# Forward tail of primer (Ftail...UMI...primer)
fwd_context: "GTATCGTGTAGAGACTGCGTAGG"

# Reverse tail of primer (Rtail...UMI...primer)
rev_context: "AGTGATCGAGTCAGTGCGAGTG"

# Forward UMI (Ftail...UMI...primer)
fwd_umi: "TTTVVVVTTVVVVTTVVVVTTVVVVTTT"

# Reverse UMI (Rtail...UMI...primer)
rev_umi: "AAABBBBAABBBBAABBBBAABBBBAAA"

# Minimum combined UMI length
min_length: 40

# Maximum combined UMI length
max_length: 60

